version: '3.7'

services:
  app:
    build: .
    container_name: filamagenta-backend
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - WOO_SERVER=
      - WOO_CONSUMER_KEY=
      - WOO_CONSUMER_SECRET=
    volumes:
      - keys:/usr/src/app/keys
