name: docker-ci

on:
  push:
    branches:
      - 'master'

permissions: write-all

concurrency:
  group: docker-ci

jobs:
  docker:
    runs-on: ubuntu-latest
    name: 🐋 Docker CI
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: arnyminerz/filamagenta-webapp:development
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          build-args: |
            version=development
            release=false
